stages:
    - test
    - run

echo_env:
    stage: test
    image: golang:1.14-alpine
    tags:
        - local-runner
    script:
        - go build -o exponet -ldflags="-X exponet/storage.dsn='${APP_DSN}'" cmd/main.go
        - chmod 700 ./exponet

run_binary:
    stage: run
    tags:
        - local-shell-runner
    dependencies: ["echo_env"]
    script:
        - echo $(pwd)
        - ls -la
        - cp ./exponet ~/${CI_PIPELINE_ID}