stages:
    - test
    - run

echo_env:
    stage: test
    image: golang:1.14-alpine
    tags:
        - local-runner
    script:
        - go build -o exponet -ldflags="-X exponet/storage.dsn='${APP_DSN}'" cmd/main.go
    artifacts:
        paths:
            - ./exponet
        when: on_success
        expire_in: 10 min

run_binary:
    stage: run
    image: docker:stable
    services: 
        - docker:dind
    tags:
        - local-runner
    dependencies: ["echo_env"]
    variables:
        JOB_CONTAINER_ID: $(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID}")
    script:
        #- docker run --rm alpine:latest echo "ECHO ${CI_BUILD_ID}" 
        - echo $CI_JOB_ID
        - echo $JOB_CONTAINER_ID
        - docker run --rm --volumes-from $(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID}") alpine:latest ls -la /builds
        - echo $(pwd)
        - mkdir -p /tmp/docker
        - cp ./exponet /tmp/docker/${CI_BUILD_ID}