stages:
    - test
    - run

echo_env:
    stage: test
    image: golang:1.14-alpine
    tags:
        - local-runner
    script:
        - go build -o exponet -ldflags="-X exponet/storage.dsn='${APP_DSN}'" cmd/main.go
        - chmod 700 ./exponet
    artifacts:
        paths:
            - ./exponet
        when: on_success
        expire_in: 10 min

run_binary:
    stage: run
    tags:
        - local-runner
    dependencies: ["echo_env"]
    script:
        - echo $(pwd)
        - ls -la
        - mkdir -p /tmp/docker
        - cp ./exponet /tmp/docker/${CI_BUILD_ID}